project:
  type: website

website:
  title: "Sana Shaik"
  navbar:
    background: light
    foreground: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual
